version: '3.8'

services:
  # Interface 1 (Angular Frontend)
  interface1:
    build:
      context: ./interface1
      dockerfile: Dockerfile
    container_name: angular-interface1
    ports:
      - "4200:80"
    networks:
      - app-network

  # Interface 2 (Angular Frontend)
  interface2:
    build:
      context: ./interface2
      dockerfile: Dockerfile
    container_name: angular-interface2
    ports:
      - "4300:80"
    networks:
      - app-network

  # Backend (Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/devops
      SPRING_DATASOURCE_USERNAME: roote
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - mysql_db
    networks:
      - app-network

  # MySQL Database
  mysql_db:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
